build algorand:
  extends: .generic-build
  variables:
    FULLNODE: algorand
    VERSION: "4_3_0"

publish algorand:
  extends: .generic-publish
  variables:
    FULLNODE: algorand
    VERSION: "4_3_0"
