build cosmos-gaia:
  extends: .generic-build
  variables:
    FULLNODE: cosmos-gaia
    VERSION: "9_0_2"

publish cosmos-gaia:
  extends: .generic-publish
  variables:
    FULLNODE: cosmos-gaia
    VERSION: "9_0_2"
