build bitcoin-zmce:
  extends: .generic-build
  variables:
    FULLNODE: bitcoin-zmce
    VERSION: "28_1"

publish bitcoin-zmce:
  extends: .generic-publish
  variables:
    FULLNODE: bitcoin-zmce
    PRIVATE: "true"
    VERSION: "28_1"
