build bitcoin-zmce:
  extends: .generic-build
  variables:
    FULLNODE: bitcoin-zmce
    VERSION: "29_0"

publish bitcoin-zmce:
  extends: .generic-publish
  variables:
    FULLNODE: bitcoin-zmce
    PRIVATE: "true"
    VERSION: "29_0"
