build monero:
  extends: .generic-build
  variables:
    FULLNODE: monero
    VERSION: "0_18_4_1"

publish monero:
  extends: .generic-publish
  variables:
    FULLNODE: monero
    VERSION: "0_18_4_1"
