build litecoin:
  extends: .generic-build
  variables:
    FULLNODE: litecoin
    VERSION: "0_21_5_6"

publish litecoin:
  extends: .generic-publish
  variables:
    FULLNODE: litecoin
    VERSION: "0_21_5_6"
